// client/src/components/dashboard/budget-calculator.tsx
import { useState } from "react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Lightbulb } from "lucide-react";

export default function BudgetCalculator() {
  const [calculationMode, setCalculationMode] = useState<'pre' | 'post'>('pre');
  const [budget, setBudget] = useState({
    total: '10000',
    smsPercent: '40',
    emailPercent: '30',
    whatsappPercent: '20',
    pushPercent: '10'
  });

  const [projectedMetrics] = useState({
    reach: '45,000 users',
    conversions: '3,780 (8.4%)',
    revenue: '$28,350',
    roi: '184%'
  });

  const handleBudgetChange = (field: string, value: string) => {
    setBudget(prev => ({ ...prev, [field]: value }));
  };

  const calculateROI = () => {
    // TODO: Implement actual ROI calculation logic
    console.log('Calculating ROI with budget:', budget);
  };

  return (
    <Card>
      <CardHeader>
        <div className="flex items-center justify-between">
          <CardTitle>Budget vs Performance Calculator</CardTitle>
          <div className="flex bg-slate-100 rounded-lg p-1">
            <Button
              variant={calculationMode === 'pre' ? 'default' : 'ghost'}
              size="sm"
              onClick={() => setCalculationMode('pre')}
              className="px-4 py-2"
            >
              Pre-Campaign
            </Button>
            <Button
              variant={calculationMode === 'post' ? 'default' : 'ghost'}
              size="sm"
              onClick={() => setCalculationMode('post')}
              className="px-4 py-2"
            >
              Post-Campaign
            </Button>
          </div>
        </div>
      </CardHeader>
      <CardContent>
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
          {/* Budget Planning */}
          <div className="space-y-4">
            <h4 className="font-medium text-slate-900">Budget Planning</h4>
            <div className="space-y-3">
              <div>
                <Label htmlFor="total-budget" className="text-sm font-medium text-slate-700">
                  Total Budget
                </Label>
                <Input
                  id="total-budget"
                  type="number"
                  value={budget.total}
                  onChange={(e) => handleBudgetChange('total', e.target.value)}
                  placeholder="10000"
                  className="mt-1"
                />
              </div>
              <div className="grid grid-cols-2 gap-3">
                <div>
                  <Label htmlFor="sms-percent" className="text-sm font-medium text-slate-700">
                    SMS (%)
                  </Label>
                  <Input
                    id="sms-percent"
                    type="number"
                    value={budget.smsPercent}
                    onChange={(e) => handleBudgetChange('smsPercent', e.target.value)}
                    placeholder="40"
                    className="mt-1"
                  />
                </div>
                <div>
                  <Label htmlFor="email-percent" className="text-sm font-medium text-slate-700">
                    Email (%)
                  </Label>
                  <Input
                    id="email-percent"
                    type="number"
                    value={budget.emailPercent}
                    onChange={(e) => handleBudgetChange('emailPercent', e.target.value)}
                    placeholder="30"
                    className="mt-1"
                  />
                </div>
              </div>
              <div className="grid grid-cols-2 gap-3">
                <div>
                  <Label htmlFor="whatsapp-percent" className="text-sm font-medium text-slate-700">
                    WhatsApp (%)
                  </Label>
                  <Input
                    id="whatsapp-percent"
                    type="number"
                    value={budget.whatsappPercent}
                    onChange={(e) => handleBudgetChange('whatsappPercent', e.target.value)}
                    placeholder="20"
                    className="mt-1"
                  />
                </div>
                <div>
                  <Label htmlFor="push-percent" className="text-sm font-medium text-slate-700">
                    Push (%)
                  </Label>
                  <Input
                    id="push-percent"
                    type="number"
                    value={budget.pushPercent}
                    onChange={(e) => handleBudgetChange('pushPercent', e.target.value)}
                    placeholder="10"
                    className="mt-1"
                  />
                </div>
              </div>
            </div>
            <Button onClick={calculateROI} className="w-full bg-primary text-white hover:bg-blue-600">
              Calculate Projected ROI
            </Button>
          </div>

          {/* Performance Metrics */}
          <div className="space-y-4">
            <h4 className="font-medium text-slate-900">
              {calculationMode === 'pre' ? 'Projected Performance' : 'Actual Performance'}
            </h4>
            <div className="bg-slate-50 rounded-lg p-4 space-y-3">
              <div className="flex justify-between">
                <span className="text-sm text-slate-600">
                  {calculationMode === 'pre' ? 'Estimated Reach' : 'Actual Reach'}
                </span>
                <span className="font-medium">{projectedMetrics.reach}</span>
              </div>
              <div className="flex justify-between">
                <span className="text-sm text-slate-600">
                  {calculationMode === 'pre' ? 'Expected Conversions' : 'Actual Conversions'}
                </span>
                <span className="font-medium">{projectedMetrics.conversions}</span>
              </div>
              <div className="flex justify-between">
                <span className="text-sm text-slate-600">
                  {calculationMode === 'pre' ? 'Projected Revenue' : 'Actual Revenue'}
                </span>
                <span className="font-medium text-green-600">{projectedMetrics.revenue}</span>
              </div>
              <div className="flex justify-between border-t border-slate-200 pt-3">
                <span className="text-sm font-medium text-slate-900">
                  {calculationMode === 'pre' ? 'Expected ROI' : 'Actual ROI'}
                </span>
                <span className="font-bold text-green-600">{projectedMetrics.roi}</span>
              </div>
            </div>
            
            <div className="bg-blue-50 border border-blue-200 rounded-lg p-4">
              <div className="flex items-start space-x-3">
                <div className="bg-blue-500 p-1 rounded">
                  <Lightbulb className="h-4 w-4 text-white" />
                </div>
                <div>
                  <h5 className="font-medium text-blue-900">AI Recommendation</h5>
                  <p className="text-sm text-blue-700 mt-1">
                    {calculationMode === 'pre' 
                      ? 'Allocate 15% more budget to WhatsApp for 23% higher conversion potential.'
                      : 'Based on results, consider shifting 10% of SMS budget to email for next campaign.'
                    }
                  </p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </CardContent>
    </Card>
  );
}

// src/app/components/budget-calculator/budget-calculator.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-budget-calculator',
  templateUrl: './budget-calculator.component.html',
  styleUrls: ['./budget-calculator.component.scss']
})
export class BudgetCalculatorComponent implements OnInit {
  budgetPlan = {
    totalBudget: 10000,
    smsPercentage: 40,
    emailPercentage: 30,
    whatsappPercentage: 20,
    pushPercentage: 10
  };

  projectedPerformance = {
    estimatedReach: 45000,
    expectedConversions: 3780,
    conversionRate: 8.4,
    projectedRevenue: 28350,
    expectedROI: 184
  };

  aiRecommendation = {
    title: 'AI Recommendation',
    message: 'Allocate 15% more budget to WhatsApp for 23% higher conversion potential.',
    confidence: 92
  };

  activeTab = 'pre-campaign';

  constructor() { }

  ngOnInit(): void {
    this.calculateProjectedPerformance();
  }

  onBudgetChange(): void {
    this.calculateProjectedPerformance();
  }

  calculateProjectedPerformance(): void {
    // Simulate ROI calculation based on budget allocation
    const totalBudget = this.budgetPlan.totalBudget;
    const weightedConversion = (
      (this.budgetPlan.smsPercentage * 0.08) +
      (this.budgetPlan.emailPercentage * 0.06) +
      (this.budgetPlan.whatsappPercentage * 0.12) +
      (this.budgetPlan.pushPercentage * 0.04)
    ) / 100;

    this.projectedPerformance.estimatedReach = Math.round(totalBudget * 4.5);
    this.projectedPerformance.expectedConversions = Math.round(this.projectedPerformance.estimatedReach * weightedConversion);
    this.projectedPerformance.conversionRate = parseFloat((weightedConversion * 100).toFixed(1));
    this.projectedPerformance.projectedRevenue = Math.round(this.projectedPerformance.expectedConversions * 7.5);
    this.projectedPerformance.expectedROI = Math.round((this.projectedPerformance.projectedRevenue / totalBudget) * 100);
  }

  calculateProjectedROI(): void {
    this.calculateProjectedPerformance();
  }

  setActiveTab(tab: string): void {
    this.activeTab = tab;
  }

  getChannelAllocation(channel: string): number {
    return Math.round((this.budgetPlan.totalBudget * this.budgetPlan[channel + 'Percentage']) / 100);
  }
}
<p-card styleClass="budget-calculator-card">
  <ng-template pTemplate="header">
    <div class="flex align-items-center justify-content-between p-4">
      <h3 class="text-lg font-semibold m-0">Budget vs Performance Calculator</h3>
      <div class="flex">
        <p-button 
          label="Pre-Campaign" 
          styleClass="p-button-sm"
          [class]="activeTab === 'pre-campaign' ? 'p-button-primary' : 'p-button-outlined'"
          (onClick)="setActiveTab('pre-campaign')">
        </p-button>
        <p-button 
          label="Post-Campaign" 
          styleClass="p-button-sm ml-2"
          [class]="activeTab === 'post-campaign' ? 'p-button-primary' : 'p-button-outlined'"
          (onClick)="setActiveTab('post-campaign')">
        </p-button>
      </div>
    </div>
  </ng-template>

  <div class="p-4">
    <div class="grid">
      <!-- Budget Planning Section -->
      <div class="col-12 md:col-6">
        <h4 class="text-base font-semibold mb-3">Budget Planning</h4>
        
        <div class="field mb-4">
          <label for="totalBudget" class="text-sm font-medium text-600 block mb-2">Total Budget</label>
          <p-inputNumber 
            id="totalBudget"
            [(ngModel)]="budgetPlan.totalBudget"
            mode="currency" 
            currency="USD"
            locale="en-US"
            [style]="{'width': '100%'}"
            (onInput)="onBudgetChange()">
          </p-inputNumber>
        </div>

        <div class="grid">
          <div class="col-6">
            <div class="field">
              <label class="text-sm font-medium text-600 block mb-2">SMS (%)</label>
              <p-inputNumber 
                [(ngModel)]="budgetPlan.smsPercentage"
                [style]="{'width': '100%'}"
                suffix="%"
                (onInput)="onBudgetChange()">
              </p-inputNumber>
            </div>
          </div>
          <div class="col-6">
            <div class="field">
              <label class="text-sm font-medium text-600 block mb-2">Email (%)</label>
              <p-inputNumber 
                [(ngModel)]="budgetPlan.emailPercentage"
                [style]="{'width': '100%'}"
                suffix="%"
                (onInput)="onBudgetChange()">
              </p-inputNumber>
            </div>
          </div>
          <div class="col-6">
            <div class="field">
              <label class="text-sm font-medium text-600 block mb-2">WhatsApp (%)</label>
              <p-inputNumber 
                [(ngModel)]="budgetPlan.whatsappPercentage"
                [style]="{'width': '100%'}"
                suffix="%"
                (onInput)="onBudgetChange()">
              </p-inputNumber>
            </div>
          </div>
          <div class="col-6">
            <div class="field">
              <label class="text-sm font-medium text-600 block mb-2">Push (%)</label>
              <p-inputNumber 
                [(ngModel)]="budgetPlan.pushPercentage"
                [style]="{'width': '100%'}"
                suffix="%"
                (onInput)="onBudgetChange()">
              </p-inputNumber>
            </div>
          </div>
        </div>

        <p-button 
          label="Calculate Projected ROI"
          styleClass="w-full p-button-primary"
          (onClick)="calculateProjectedROI()">
        </p-button>
      </div>

      <!-- Projected Performance Section -->
      <div class="col-12 md:col-6">
        <h4 class="text-base font-semibold mb-3">Projected Performance</h4>
        
        <div class="performance-metrics">
          <div class="metric-row flex align-items-center justify-content-between mb-3">
            <span class="text-sm text-600">Estimated Reach</span>
            <span class="font-semibold">{{projectedPerformance.estimatedReach | number}} users</span>
          </div>
          
          <div class="metric-row flex align-items-center justify-content-between mb-3">
            <span class="text-sm text-600">Expected Conversions</span>
            <span class="font-semibold">{{projectedPerformance.expectedConversions | number}} ({{projectedPerformance.conversionRate}}%)</span>
          </div>
          
          <div class="metric-row flex align-items-center justify-content-between mb-3">
            <span class="text-sm text-600">Projected Revenue</span>
            <span class="font-semibold text-green-600">${{projectedPerformance.projectedRevenue | number}}</span>
          </div>
          
          <div class="metric-row flex align-items-center justify-content-between mb-4">
            <span class="text-sm text-600">Expected ROI</span>
            <span class="font-semibold text-green-600">{{projectedPerformance.expectedROI}}%</span>
          </div>
        </div>

        <!-- AI Recommendation -->
        <div class="ai-recommendation bg-blue-50 border-round-lg p-3">
          <div class="flex align-items-center gap-2 mb-2">
            <i class="pi pi-lightbulb text-blue-600"></i>
            <span class="font-semibold text-blue-900">{{aiRecommendation.title}}</span>
          </div>
          <p class="text-sm text-blue-800 m-0">{{aiRecommendation.message}}</p>
        </div>
      </div>
    </div>
  </div>
</p-card>
