// src/app/components/heat-map/heat-map.component.ts
import { Component, OnInit } from '@angular/core';

interface HeatMapCell {
  value: number;
  intensity: 'low' | 'medium' | 'high';
}

@Component({
  selector: 'app-heat-map',
  templateUrl: './heat-map.component.html',
  styleUrls: ['./heat-map.component.scss']
})
export class HeatMapComponent implements OnInit {
  selectedMetric = 'Engagement Rate';
  metricOptions = [
    { label: 'Engagement Rate', value: 'Engagement Rate' },
    { label: 'Conversion Rate', value: 'Conversion Rate' },
    { label: 'ROI', value: 'ROI' }
  ];

  heatMapData: HeatMapCell[] = [
    { value: 85, intensity: 'high' },
    { value: 45, intensity: 'low' },
    { value: 67, intensity: 'medium' },
    { value: 92, intensity: 'high' },
    { value: 23, intensity: 'low' },
    { value: 78, intensity: 'medium' },
    { value: 56, intensity: 'medium' },
    { value: 81, intensity: 'high' },
    { value: 94, intensity: 'high' },
    { value: 62, intensity: 'medium' },
    { value: 34, intensity: 'low' },
    { value: 76, intensity: 'medium' },
    { value: 58, intensity: 'medium' },
    { value: 87, intensity: 'high' }
  ];

  constructor() { }

  ngOnInit(): void { }

  getCellClass(intensity: string): string {
    switch (intensity) {
      case 'high': return 'heat-cell high';
      case 'medium': return 'heat-cell medium';
      case 'low': return 'heat-cell low';
      default: return 'heat-cell';
    }
  }
}
<p-card header="Campaign Performance Heat Map">
  <ng-template pTemplate="header">
    <div class="flex align-items-center justify-content-between p-4">
      <h3 class="text-lg font-semibold m-0">Campaign Performance Heat Map</h3>
      <p-dropdown 
        [options]="metricOptions" 
        [(ngModel)]="selectedMetric"
        optionLabel="label"
        optionValue="value"
        [style]="{'min-width': '150px'}">
      </p-dropdown>
    </div>
  </ng-template>
  
  <div class="heat-map-grid">
    <div *ngFor="let cell of heatMapData" 
         [ngClass]="getCellClass(cell.intensity)"
         [attr.title]="selectedMetric + ': ' + cell.value + '%'">
      {{cell.value}}
    </div>
  </div>
  
  <div class="flex align-items-center justify-content-between mt-4 text-xs text-500">
    <span>Low</span>
    <div class="flex align-items-center gap-1">
      <div class="w-1rem h-1rem bg-red-100 border-round"></div>
      <div class="w-1rem h-1rem bg-orange-100 border-round"></div>
      <div class="w-1rem h-1rem bg-green-100 border-round"></div>
      <div class="w-1rem h-1rem bg-green-200 border-round"></div>
    </div>
    <span>High</span>
  </div>
</p-card>

// client/src/components/dashboard/heat-map.tsx
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { useState } from "react";

export default function HeatMap() {
  const [selectedMetric, setSelectedMetric] = useState("engagement_rate");

  // Mock heat map data - 14 cells for simplified 2-week view
  const heatMapData = [
    { value: 85, intensity: 'high' },
    { value: 45, intensity: 'low' },
    { value: 67, intensity: 'medium' },
    { value: 92, intensity: 'high' },
    { value: 23, intensity: 'low' },
    { value: 78, intensity: 'medium' },
    { value: 56, intensity: 'medium' },
    { value: 81, intensity: 'high' },
    { value: 94, intensity: 'high' },
    { value: 62, intensity: 'medium' },
    { value: 34, intensity: 'low' },
    { value: 76, intensity: 'medium' },
    { value: 58, intensity: 'medium' },
    { value: 87, intensity: 'high' },
  ];

  const getIntensityColor = (intensity: string) => {
    switch (intensity) {
      case 'high': return 'bg-green-200 text-green-800 hover:bg-green-300';
      case 'medium': return 'bg-amber-100 text-amber-800 hover:bg-amber-200';
      case 'low': return 'bg-red-100 text-red-800 hover:bg-red-200';
      default: return 'bg-slate-100 text-slate-600 hover:bg-slate-200';
    }
  };

  return (
    <Card>
      <CardHeader>
        <div className="flex items-center justify-between">
          <CardTitle>Campaign Performance Heat Map</CardTitle>
          <Select value={selectedMetric} onValueChange={setSelectedMetric}>
            <SelectTrigger className="w-[150px]">
              <SelectValue />
            </SelectTrigger>
            <SelectContent>
              <SelectItem value="engagement_rate">Engagement Rate</SelectItem>
              <SelectItem value="conversion_rate">Conversion Rate</SelectItem>
              <SelectItem value="roi">ROI</SelectItem>
            </SelectContent>
          </Select>
        </div>
      </CardHeader>
      <CardContent>
        <div className="grid grid-cols-7 gap-1">
          {heatMapData.map((cell, index) => (
            <div
              key={index}
              className={`aspect-square rounded text-xs flex items-center justify-center cursor-pointer transition-colors ${getIntensityColor(cell.intensity)}`}
              title={`${selectedMetric}: ${cell.value}%`}
            >
              {cell.value}
            </div>
          ))}
        </div>
        <div className="flex items-center justify-between mt-4 text-xs text-slate-500">
          <span>Low</span>
          <div className="flex items-center space-x-1">
            <div className="w-3 h-3 bg-red-100 rounded"></div>
            <div className="w-3 h-3 bg-amber-100 rounded"></div>
            <div className="w-3 h-3 bg-green-100 rounded"></div>
            <div className="w-3 h-3 bg-green-200 rounded"></div>
          </div>
          <span>High</span>
        </div>
      </CardContent>
    </Card>
  );
}
