// client/src/components/dashboard/campaign-monitoring.tsx
import { useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Badge } from "@/components/ui/badge";
import { ChevronLeft, ChevronRight, Clock, Pause, Play, Edit3, LayoutGrid, List } from "lucide-react";

interface CampaignMonitoringProps {
  onViewDetails: (campaignId: string) => void;
}

export default function CampaignMonitoring({ onViewDetails }: CampaignMonitoringProps) {
  const [viewMode, setViewMode] = useState<'cards' | 'table'>('cards');
  const [statusFilter, setStatusFilter] = useState('all');
  const [currentPage, setCurrentPage] = useState(0);
  const cardsPerPage = 3;

  const { data: campaigns, isLoading } = useQuery({
    queryKey: ["/api/campaigns"],
  });

  if (isLoading) {
    return (
      <Card>
        <CardHeader>
          <CardTitle>Real-time Campaign Monitoring</CardTitle>
        </CardHeader>
        <CardContent>
          <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
            {[...Array(3)].map((_, i) => (
              <div key={i} className="animate-pulse border border-slate-200 rounded-xl p-6">
                <div className="h-32 bg-slate-200 rounded"></div>
              </div>
            ))}
          </div>
        </CardContent>
      </Card>
    );
  }

  const filteredCampaigns = campaigns?.filter((campaign: any) => 
    statusFilter === 'all' || campaign.status === statusFilter
  ) || [];

  const paginatedCampaigns = filteredCampaigns.slice(
    currentPage * cardsPerPage,
    (currentPage + 1) * cardsPerPage
  );

  const totalPages = Math.ceil(filteredCampaigns.length / cardsPerPage);

  const getStatusVariant = (status: string) => {
    switch (status) {
      case 'active': return 'default';
      case 'paused': return 'destructive';
      case 'scheduled': return 'secondary';
      case 'completed': return 'outline';
      default: return 'outline';
    }
  };

  const getStatusColor = (status: string) => {
    switch (status) {
      case 'active': return 'bg-green-100 text-green-800';
      case 'paused': return 'bg-red-100 text-red-800';
      case 'scheduled': return 'bg-amber-100 text-amber-800';
      case 'completed': return 'bg-slate-100 text-slate-800';
      default: return 'bg-slate-100 text-slate-800';
    }
  };

  const formatTimeAgo = (date: string | Date) => {
    const now = new Date();
    const then = new Date(date);
    const diffInHours = Math.floor((now.getTime() - then.getTime()) / (1000 * 60 * 60));
    
    if (diffInHours < 1) return "Just now";
    if (diffInHours < 24) return `${diffInHours}h ago`;
    return `${Math.floor(diffInHours / 24)}d ago`;
  };

  return (
    <Card>
      <CardHeader>
        <div className="flex items-center justify-between">
          <CardTitle>Real-time Campaign Monitoring</CardTitle>
          <div className="flex items-center space-x-4">
            <Select value={statusFilter} onValueChange={setStatusFilter}>
              <SelectTrigger className="w-[150px]">
                <SelectValue placeholder="All Status" />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="all">All Status</SelectItem>
                <SelectItem value="active">Active</SelectItem>
                <SelectItem value="paused">Paused</SelectItem>
                <SelectItem value="scheduled">Scheduled</SelectItem>
                <SelectItem value="completed">Completed</SelectItem>
              </SelectContent>
            </Select>
            <div className="flex bg-slate-100 rounded-lg p-1">
              <Button
                variant={viewMode === 'cards' ? 'default' : 'ghost'}
                size="sm"
                onClick={() => setViewMode('cards')}
                className="px-3 py-1"
              >
                <LayoutGrid className="h-4 w-4 mr-1" />
                Cards
              </Button>
              <Button
                variant={viewMode === 'table' ? 'default' : 'ghost'}
                size="sm"
                onClick={() => setViewMode('table')}
                className="px-3 py-1"
              >
                <List className="h-4 w-4 mr-1" />
                Table
              </Button>
            </div>
          </div>
        </div>
      </CardHeader>
      <CardContent>
        {viewMode === 'cards' && (
          <div className="space-y-4">
            <div className="flex items-center justify-between">
              <div className="flex items-center space-x-2">
                <Button
                  variant="outline"
                  size="sm"
                  onClick={() => setCurrentPage(Math.max(0, currentPage - 1))}
                  disabled={currentPage === 0}
                >
                  <ChevronLeft className="h-4 w-4" />
                </Button>
                <span className="text-sm text-slate-600">
                  {currentPage * cardsPerPage + 1}-{Math.min((currentPage + 1) * cardsPerPage, filteredCampaigns.length)} of {filteredCampaigns.length} campaigns
                </span>
                <Button
                  variant="outline"
                  size="sm"
                  onClick={() => setCurrentPage(Math.min(totalPages - 1, currentPage + 1))}
                  disabled={currentPage >= totalPages - 1}
                >
                  <ChevronRight className="h-4 w-4" />
                </Button>
              </div>
              <div className="text-sm text-slate-500 flex items-center">
                <Clock className="h-4 w-4 mr-1" />
                Last updated: 2 min ago
              </div>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
              {paginatedCampaigns.map((campaign: any) => (
                <div key={campaign.id} className="border border-slate-200 rounded-xl p-6 hover:shadow-lg transition-shadow">
                  <div className="flex items-start justify-between mb-4">
                    <div>
                      <h4 className="font-semibold text-slate-900">{campaign.name}</h4>
                      <p className="text-sm text-slate-600">
                        {campaign.type} • {Array.isArray(campaign.channels) ? campaign.channels.join(' + ') : campaign.channels}
                      </p>
                    </div>
                    <div className="flex items-center space-x-2">
                      <span className={`text-xs px-2 py-1 rounded-full font-medium ${getStatusColor(campaign.status)}`}>
                        {campaign.status.charAt(0).toUpperCase() + campaign.status.slice(1)}
                      </span>
                      {campaign.status === 'active' && (
                        <Button variant="ghost" size="sm">
                          <Pause className="h-4 w-4" />
                        </Button>
                      )}
                      {campaign.status === 'paused' && (
                        <Button variant="ghost" size="sm">
                          <Play className="h-4 w-4" />
                        </Button>
                      )}
                      {campaign.status === 'scheduled' && (
                        <Button variant="ghost" size="sm">
                          <Edit3 className="h-4 w-4" />
                        </Button>
                      )}
                    </div>
                  </div>
                  
                  <div className="space-y-3">
                    {campaign.status !== 'scheduled' ? (
                      <>
                        <div className="flex justify-between text-sm">
                          <span className="text-slate-600">Sent</span>
                          <span className="font-medium">{campaign.sent?.toLocaleString() || 0}</span>
                        </div>
                        <div className="flex justify-between text-sm">
                          <span className="text-slate-600">Delivered</span>
                          <span className="font-medium">
                            {campaign.delivered?.toLocaleString() || 0} ({campaign.sent ? ((campaign.delivered / campaign.sent) * 100).toFixed(1) : 0}%)
                          </span>
                        </div>
                        <div className="flex justify-between text-sm">
                          <span className="text-slate-600">Opened</span>
                          <span className="font-medium">
                            {campaign.opened?.toLocaleString() || 0} ({campaign.sent ? ((campaign.opened / campaign.sent) * 100).toFixed(1) : 0}%)
                          </span>
                        </div>
                        <div className="flex justify-between text-sm">
                          <span className="text-slate-600">Clicked</span>
                          <span className="font-medium">
                            {campaign.clicked?.toLocaleString() || 0} ({campaign.sent ? ((campaign.clicked / campaign.sent) * 100).toFixed(1) : 0}%)
                          </span>
                        </div>
                      </>
                    ) : (
                      <>
                        <div className="flex justify-between text-sm">
                          <span className="text-slate-600">Target Audience</span>
                          <span className="font-medium">{campaign.targetAudience?.toLocaleString()}</span>
                        </div>
                        <div className="flex justify-between text-sm">
                          <span className="text-slate-600">Estimated Cost</span>
                          <span className="font-medium">${campaign.cost}</span>
                        </div>
                        <div className="flex justify-between text-sm">
                          <span className="text-slate-600">Channel</span>
                          <span className="font-medium">
                            {Array.isArray(campaign.channels) ? campaign.channels.join(', ') : campaign.channels}
                          </span>
                        </div>
                        {campaign.scheduledAt && (
                          <div className="bg-slate-50 rounded-lg p-3">
                            <div className="text-xs text-slate-600 mb-1">Scheduled for:</div>
                            <div className="text-sm font-medium text-slate-900">
                              {new Date(campaign.scheduledAt).toLocaleDateString()} at {new Date(campaign.scheduledAt).toLocaleTimeString()}
                            </div>
                          </div>
                        )}
                      </>
                    )}

                    {campaign.status === 'paused' && (
                      <div className="bg-amber-50 rounded-lg p-3 border border-amber-200">
                        <div className="text-xs text-amber-700 font-medium mb-1 flex items-center">
                          <Pause className="h-3 w-3 mr-1" />
                          Campaign Paused
                        </div>
                        <div className="text-xs text-amber-600">Paused due to low engagement</div>
                      </div>
                    )}
                  </div>
                  
                  <div className="mt-4 pt-4 border-t border-slate-200 flex items-center justify-between">
                    <div className="text-xs text-slate-500">
                      {campaign.status === 'scheduled' ? 'Created' : 
                       campaign.status === 'paused' ? 'Paused' : 'Started'}: {' '}
                      <span>
                        {formatTimeAgo(
                          campaign.status === 'scheduled' ? campaign.createdAt :
                          campaign.status === 'paused' ? campaign.pausedAt :
                          campaign.startedAt
                        )}
                      </span>
                    </div>
                    <Button 
                      variant="ghost" 
                      size="sm"
                      onClick={() => onViewDetails(campaign.id)}
                      className="text-primary hover:text-blue-600"
                    >
                      View Details
                    </Button>
                  </div>
                </div>
              ))}
            </div>
          </div>
        )}
      </CardContent>
    </Card>
  );
}

// src/app/components/campaign-monitoring/campaign-monitoring.component.ts
import { Component, OnInit } from '@angular/core';

interface Campaign {
  id: string;
  name: string;
  type: string;
  status: 'active' | 'paused' | 'scheduled' | 'completed';
  channels: string[];
  targetAudience: number;
  sent: number;
  delivered: number;
  opened: number;
  clicked: number;
  converted: number;
  conversions: number;
  spent: number;
  budget: number;
  cost: string;
  createdAt: Date;
  startedAt?: Date;
  scheduledAt?: Date;
  pausedAt?: Date;
}

@Component({
  selector: 'app-campaign-monitoring',
  templateUrl: './campaign-monitoring.component.html',
  styleUrls: ['./campaign-monitoring.component.scss']
})
export class CampaignMonitoringComponent implements OnInit {
  campaigns: Campaign[] = [
    {
      id: '1',
      name: 'Summer Sale Campaign',
      type: 'Promotional',
      status: 'active',
      channels: ['SMS', 'Email'],
      targetAudience: 15234,
      sent: 15234,
      delivered: 14892,
      opened: 10234,
      clicked: 3567,
      converted: 1234,
      conversions: 1234,
      spent: 1250,
      budget: 2000,
      cost: '1250.00',
      createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
      startedAt: new Date(Date.now() - 6 * 60 * 60 * 1000)
    },
    {
      id: '2',
      name: 'Welcome Series',
      type: 'Onboarding',
      status: 'scheduled',
      channels: ['WhatsApp'],
      targetAudience: 2457,
      sent: 0,
      delivered: 0,
      opened: 0,
      clicked: 0,
      converted: 0,
      conversions: 0,
      spent: 189,
      budget: 500,
      cost: '189.00',
      createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
      scheduledAt: new Date(Date.now() + 18 * 60 * 60 * 1000)
    },
    {
      id: '3',
      name: 'Product Launch',
      type: 'Announcement',
      status: 'paused',
      channels: ['SMS', 'Email', 'Push'],
      targetAudience: 8543,
      sent: 8543,
      delivered: 8234,
      opened: 4567,
      clicked: 1234,
      converted: 456,
      conversions: 456,
      spent: 567,
      budget: 1000,
      cost: '567.00',
      createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
      startedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
      pausedAt: new Date(Date.now() - 1 * 60 * 60 * 1000)
    }
  ];

  currentPage = 0;
  campaignsPerPage = 3;
  selectedStatus = 'All Status';
  viewMode = 'cards'; // 'cards' or 'table'

  statusOptions = [
    { label: 'All Status', value: 'All Status' },
    { label: 'Active', value: 'Active' },
    { label: 'Paused', value: 'Paused' },
    { label: 'Scheduled', value: 'Scheduled' }
  ];

  selectedCampaign: Campaign | null = null;
  showCampaignModal = false;
  Math = Math; // Make Math available in template

  constructor() { }

  ngOnInit(): void { }

  get filteredCampaigns(): Campaign[] {
    let filtered = this.campaigns;
    
    // Filter by status
    if (this.selectedStatus !== 'All Status') {
      filtered = filtered.filter(campaign => 
        campaign.status.toLowerCase() === this.selectedStatus.toLowerCase()
      );
    }
    
    return filtered;
  }

  get paginatedCampaigns(): Campaign[] {
    const startIndex = this.currentPage * this.campaignsPerPage;
    const endIndex = startIndex + this.campaignsPerPage;
    return this.filteredCampaigns.slice(startIndex, endIndex);
  }

  get totalPages(): number {
    return Math.ceil(this.filteredCampaigns.length / this.campaignsPerPage);
  }

  previousPage(): void {
    this.currentPage = Math.max(0, this.currentPage - 1);
  }

  nextPage(): void {
    this.currentPage = Math.min(this.totalPages - 1, this.currentPage + 1);
  }

  getStatusClass(status: string): string {
    switch (status) {
      case 'active': return 'campaign-status active';
      case 'paused': return 'campaign-status paused';
      case 'scheduled': return 'campaign-status scheduled';
      case 'completed': return 'campaign-status completed';
      default: return 'campaign-status';
    }
  }

  getDeliveryRate(campaign: Campaign): string {
    return campaign.sent ? ((campaign.delivered / campaign.sent) * 100).toFixed(1) : '0';
  }

  getOpenRate(campaign: Campaign): string {
    return campaign.sent ? ((campaign.opened / campaign.sent) * 100).toFixed(1) : '0';
  }

  getClickRate(campaign: Campaign): string {
    return campaign.sent ? ((campaign.clicked / campaign.sent) * 100).toFixed(1) : '0';
  }

  formatTimeAgo(date: Date): string {
    const now = new Date();
    const diffInHours = Math.floor((now.getTime() - date.getTime()) / (1000 * 60 * 60));
    
    if (diffInHours < 1) return "Just now";
    if (diffInHours < 24) return `${diffInHours}h ago`;
    return `${Math.floor(diffInHours / 24)}d ago`;
  }

  viewCampaignDetails(campaign: Campaign): void {
    this.selectedCampaign = campaign;
    this.showCampaignModal = true;
  }

  closeCampaignModal(): void {
    this.showCampaignModal = false;
    this.selectedCampaign = null;
  }

  toggleCampaignStatus(campaign: Campaign): void {
    if (campaign.status === 'active') {
      campaign.status = 'paused';
      campaign.pausedAt = new Date();
    } else if (campaign.status === 'paused') {
      campaign.status = 'active';
      campaign.startedAt = new Date();
    }
  }
}
<p-card header="Real-time Campaign Monitoring">
  <ng-template pTemplate="header">
    <div class="flex align-items-center justify-content-between p-4">
      <h3 class="text-lg font-semibold m-0">Real-time Campaign Monitoring</h3>
      <div class="flex align-items-center gap-4">
        <p-dropdown 
          [options]="statusOptions" 
          [(ngModel)]="selectedStatus"
          optionLabel="label"
          optionValue="value"
          [style]="{'min-width': '120px'}">
        </p-dropdown>
        <div class="flex bg-surface-100 border-round-lg p-1">
          <p-button 
            label="Cards" 
            icon="pi pi-th-large"
            styleClass="p-button-sm"
            [class]="viewMode === 'cards' ? 'p-button-primary' : 'p-button-outlined'"
            (onClick)="viewMode = 'cards'">
          </p-button>
          <p-button 
            label="Table" 
            icon="pi pi-list"
            styleClass="p-button-sm"
            [class]="viewMode === 'table' ? 'p-button-primary' : 'p-button-outlined'"
            (onClick)="viewMode = 'table'">
          </p-button>
        </div>
      </div>
    </div>
  </ng-template>

  <!-- Pagination Controls -->
  <div class="flex align-items-center justify-content-between mb-4">
    <div class="flex align-items-center gap-2">
      <p-button 
        icon="pi pi-chevron-left"
        styleClass="p-button-outlined p-button-sm"
        [disabled]="currentPage === 0"
        (onClick)="previousPage()">
      </p-button>
      <span class="text-sm text-600">
        {{currentPage * campaignsPerPage + 1}}-{{Math.min((currentPage + 1) * campaignsPerPage, campaigns.length)}} of {{campaigns.length}} campaigns
      </span>
      <p-button 
        icon="pi pi-chevron-right"
        styleClass="p-button-outlined p-button-sm"
        [disabled]="currentPage >= totalPages - 1"
        (onClick)="nextPage()">
      </p-button>
    </div>
    <div class="text-sm text-500 flex align-items-center">
      <i class="pi pi-clock mr-1"></i>
      Last updated: 2 min ago
    </div>
  </div>

  <!-- Cards View -->
  <div *ngIf="viewMode === 'cards'" class="grid">
    <div class="col-12 md:col-6 lg:col-4" *ngFor="let campaign of paginatedCampaigns">
      <div class="campaign-card">
        <div class="flex align-items-start justify-content-between mb-4">
          <div>
            <h4 class="font-semibold text-900 m-0 mb-1">{{campaign.name}}</h4>
            <p class="text-sm text-600 m-0">
              {{campaign.type}} • {{campaign.channels.join(' + ')}}
            </p>
          </div>
          <div class="flex align-items-center gap-2">
            <p-tag 
              [value]="campaign.status" 
              [ngClass]="getStatusClass(campaign.status)"
              styleClass="text-xs">
            </p-tag>
            <p-button 
              *ngIf="campaign.status === 'active'"
              icon="pi pi-pause"
              styleClass="p-button-text p-button-sm"
              (onClick)="toggleCampaignStatus(campaign)">
            </p-button>
            <p-button 
              *ngIf="campaign.status === 'paused'"
              icon="pi pi-play"
              styleClass="p-button-text p-button-sm"
              (onClick)="toggleCampaignStatus(campaign)">
            </p-button>
          </div>
        </div>
        
        <div class="flex flex-column gap-3">
          <div *ngIf="campaign.status !== 'scheduled'">
            <div class="flex justify-content-between text-sm mb-2">
              <span class="text-600">Sent</span>
              <span class="font-medium">{{campaign.sent | number}}</span>
            </div>
            <div class="flex justify-content-between text-sm mb-2">
              <span class="text-600">Delivered</span>
              <span class="font-medium">{{campaign.delivered | number}} ({{getDeliveryRate(campaign)}}%)</span>
            </div>
            <div class="flex justify-content-between text-sm mb-2">
              <span class="text-600">Opened</span>
              <span class="font-medium">{{campaign.opened | number}} ({{getOpenRate(campaign)}}%)</span>
            </div>
            <div class="flex justify-content-between text-sm">
              <span class="text-600">Clicked</span>
              <span class="font-medium">{{campaign.clicked | number}} ({{getClickRate(campaign)}}%)</span>
            </div>
          </div>
          
          <div *ngIf="campaign.status === 'scheduled'">
            <div class="flex justify-content-between text-sm mb-2">
              <span class="text-600">Target Audience</span>
              <span class="font-medium">{{campaign.targetAudience | number}}</span>
            </div>
            <div class="flex justify-content-between text-sm">
              <span class="text-600">Estimated Cost</span>
              <span class="font-medium">${{campaign.cost}}</span>
            </div>
            <div *ngIf="campaign.scheduledAt" class="bg-surface-50 border-round-lg p-3 mt-3">
              <div class="text-xs text-600 mb-1">Scheduled for:</div>
              <div class="text-sm font-medium text-900">
                {{campaign.scheduledAt | date:'short'}}
              </div>
            </div>
          </div>

          <div *ngIf="campaign.status === 'paused'" class="bg-orange-50 border-round-lg p-3 border-1 border-orange-200">
            <div class="text-xs text-orange-700 font-medium mb-1 flex align-items-center">
              <i class="pi pi-pause mr-1"></i>
              Campaign Paused
            </div>
            <div class="text-xs text-orange-600">Paused due to low engagement</div>
          </div>
        </div>
        
        <div class="mt-4 pt-4 border-top-1 border-200 flex align-items-center justify-content-between">
          <div class="text-xs text-500">
            {{campaign.status === 'scheduled' ? 'Created' : 
              campaign.status === 'paused' ? 'Paused' : 'Started'}}: 
            <span>
              {{formatTimeAgo(
                campaign.status === 'scheduled' ? campaign.createdAt :
                campaign.status === 'paused' ? (campaign.pausedAt || campaign.createdAt) :
                (campaign.startedAt || campaign.createdAt)
              )}}
            </span>
          </div>
          <p-button 
            label="View Details" 
            styleClass="p-button-text p-button-sm text-primary"
            (onClick)="viewCampaignDetails(campaign)">
          </p-button>
        </div>
      </div>
    </div>
  </div>
</p-card>

<!-- Campaign Details Modal -->
<p-dialog 
  [(visible)]="showCampaignModal"
  [modal]="true"
  [closable]="true"
  [draggable]="false"
  [resizable]="false"
  styleClass="w-11 max-w-4xl"
  (onHide)="closeCampaignModal()">
  
  <ng-template pTemplate="header">
    <div class="flex align-items-center justify-content-between w-full">
      <h2 class="text-xl font-bold m-0">{{selectedCampaign?.name}}</h2>
      <div class="flex align-items-center gap-2">
        <p-tag 
          *ngIf="selectedCampaign"
          [value]="selectedCampaign.status" 
          [ngClass]="getStatusClass(selectedCampaign.status)">
        </p-tag>
      </div>
    </div>
  </ng-template>

  <div *ngIf="selectedCampaign">
    <!-- Campaign Overview Cards -->
    <div class="grid mb-4">
      <div class="col-12 md:col-6 lg:col-3">
        <p-card styleClass="text-center">
          <div class="text-sm font-medium text-600 flex align-items-center justify-content-center mb-1">
            <i class="pi pi-users mr-1"></i>
            Target Audience
          </div>
          <div class="text-2xl font-bold">{{selectedCampaign.targetAudience | number}}</div>
        </p-card>
      </div>
      <div class="col-12 md:col-6 lg:col-3">
        <p-card styleClass="text-center">
          <div class="text-sm font-medium text-600 flex align-items-center justify-content-center mb-1">
            <i class="pi pi-dollar mr-1"></i>
            Total Cost
          </div>
          <div class="text-2xl font-bold">${{selectedCampaign.cost}}</div>
        </p-card>
      </div>
      <div class="col-12 md:col-6 lg:col-3">
        <p-card styleClass="text-center">
          <div class="text-sm font-medium text-600 flex align-items-center justify-content-center mb-1">
            <i class="pi pi-chart-bar mr-1"></i>
            Delivery Rate
          </div>
          <div class="text-2xl font-bold">{{getDeliveryRate(selectedCampaign)}}%</div>
        </p-card>
      </div>
      <div class="col-12 md:col-6 lg:col-3">
        <p-card styleClass="text-center">
          <div class="text-sm font-medium text-600 flex align-items-center justify-content-center mb-1">
            <i class="pi pi-chart-line mr-1"></i>
            Open Rate
          </div>
          <div class="text-2xl font-bold">{{getOpenRate(selectedCampaign)}}%</div>
        </p-card>
      </div>
    </div>

    <!-- Campaign Details -->
    <p-card>
      <div class="grid">
        <div class="col-12 md:col-6">
          <label class="text-sm font-medium text-600 block mb-1">Campaign Type</label>
          <p class="text-900 m-0">{{selectedCampaign.type}}</p>
        </div>
        <div class="col-12 md:col-6">
          <label class="text-sm font-medium text-600 block mb-1">Channels</label>
          <p class="text-900 m-0">{{selectedCampaign.channels.join(', ')}}</p>
        </div>
        <div class="col-12 md:col-6">
          <label class="text-sm font-medium text-600 block mb-1">Created</label>
          <p class="text-900 m-0">{{selectedCampaign.createdAt | date:'medium'}}</p>
        </div>
        <div class="col-12 md:col-6" *ngIf="selectedCampaign.startedAt">
          <label class="text-sm font-medium text-600 block mb-1">Started</label>
          <p class="text-900 m-0">{{selectedCampaign.startedAt | date:'medium'}}</p>
        </div>
      </div>

      <!-- Action Buttons -->
      <div class="mt-4 pt-4 border-top-1 border-200 flex flex-wrap gap-2">
        <p-button 
          label="Edit Campaign" 
          icon="pi pi-pencil"
          styleClass="p-button-outlined p-button-sm">
        </p-button>
        <p-button 
          *ngIf="selectedCampaign.status === 'active'"
          label="Pause Campaign" 
          icon="pi pi-pause"
          styleClass="p-button-outlined p-button-sm"
          (onClick)="toggleCampaignStatus(selectedCampaign)">
        </p-button>
        <p-button 
          *ngIf="selectedCampaign.status === 'paused'"
          label="Resume Campaign" 
          icon="pi pi-play"
          styleClass="p-button-outlined p-button-sm"
          (onClick)="toggleCampaignStatus(selectedCampaign)">
        </p-button>
      </div>
    </p-card>
  </div>
</p-dialog>
