// client/src/components/dashboard/inactive-customers.tsx
import { useQuery } from "@tanstack/react-query";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";

export default function InactiveCustomers() {
  const { data: inactiveCustomers } = useQuery({
    queryKey: ["/api/inactive-customers"],
  });

  // Mock aggregated data since we don't have a specific endpoint for this
  const inactiveStats = {
    total: 2847,
    winbackEligible: 1234,
    highValue: 567,
    churnRisk: 1046
  };

  return (
    <Card>
      <CardHeader>
        <CardTitle>Inactive Customers</CardTitle>
      </CardHeader>
      <CardContent>
        <div className="text-center mb-4">
          <div className="text-3xl font-bold text-red-600">{inactiveStats.total.toLocaleString()}</div>
          <div className="text-sm text-slate-600">customers inactive for 30+ days</div>
        </div>
        <div className="space-y-3">
          <div className="flex justify-between text-sm">
            <span className="text-slate-600">Win-back eligible</span>
            <span className="font-medium text-green-600">{inactiveStats.winbackEligible.toLocaleString()}</span>
          </div>
          <div className="flex justify-between text-sm">
            <span className="text-slate-600">High-value customers</span>
            <span className="font-medium text-amber-600">{inactiveStats.highValue.toLocaleString()}</span>
          </div>
          <div className="flex justify-between text-sm">
            <span className="text-slate-600">Churn risk</span>
            <span className="font-medium text-red-600">{inactiveStats.churnRisk.toLocaleString()}</span>
          </div>
        </div>
        <div className="mt-4 space-y-2">
          <Button className="w-full bg-primary text-white hover:bg-blue-600">
            Create Win-back Campaign
          </Button>
          <Button variant="outline" className="w-full">
            View Detailed Report
          </Button>
        </div>
      </CardContent>
    </Card>
  );
}

// src/app/components/inactive-customers/inactive-customers.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-inactive-customers',
  templateUrl: './inactive-customers.component.html',
  styleUrls: ['./inactive-customers.component.scss']
})
export class InactiveCustomersComponent implements OnInit {
  inactiveCustomers = 2847;
  inactiveDays = 30;
  winBackEligible = 1234;
  highValueCustomers = 567;
  churnRisk = 1046;
  
  customerSegments = [
    {
      label: 'Win-back eligible',
      value: 1234,
      color: 'green',
      description: 'Customers likely to re-engage'
    },
    {
      label: 'High-value customers',
      value: 567,
      color: 'orange',
      description: 'Premium customers worth retaining'
    },
    {
      label: 'Churn risk',
      value: 1046,
      color: 'red',
      description: 'Customers at risk of churning'
    }
  ];

  constructor() { }

  ngOnInit(): void {
  }

  createWinBackCampaign(): void {
    console.log('Creating win-back campaign');
  }

  viewDetailedReport(): void {
    console.log('Viewing detailed inactive customers report');
  }
}
<p-card>
  <ng-template pTemplate="header">
    <div class="flex align-items-center justify-content-between p-4">
      <h3 class="text-lg font-semibold m-0">Inactive Customers</h3>
    </div>
  </ng-template>
  
  <div class="p-4">
    <div class="inactive-summary text-center mb-4">
      <div class="text-3xl font-bold text-red-600 mb-1">{{inactiveCustomers | number}}</div>
      <div class="text-sm text-600 mb-2">customers inactive for {{inactiveDays}}+ days</div>
    </div>
    
    <div class="customer-segments mb-4">
      <div class="segment-item flex align-items-center justify-content-between mb-3"
           *ngFor="let segment of customerSegments">
        <div class="flex align-items-center gap-3">
          <div class="segment-indicator" [ngClass]="'bg-' + segment.color + '-100'">
            <div class="w-3 h-3 border-round" [ngClass]="'bg-' + segment.color + '-500'"></div>
          </div>
          <div>
            <div class="font-medium text-900">{{segment.label}}</div>
            <div class="text-sm text-600">{{segment.description}}</div>
          </div>
        </div>
        <div class="text-right">
          <div class="font-semibold" [ngClass]="'text-' + segment.color + '-600'">
            {{segment.value | number}}
          </div>
        </div>
      </div>
    </div>
    
    <div class="action-buttons grid gap-2">
      <div class="col-12">
        <p-button 
          label="Create Win-back Campaign"
          styleClass="w-full p-button-primary"
          icon="pi pi-plus"
          (onClick)="createWinBackCampaign()">
        </p-button>
      </div>
      <div class="col-12">
        <p-button 
          label="View Detailed Report"
          styleClass="w-full p-button-outlined"
          icon="pi pi-chart-line"
          (onClick)="viewDetailedReport()">
        </p-button>
      </div>
    </div>
  </div>
</p-card>
