// client/src/components/dashboard/bsp-comparison.tsx
import { useQuery } from "@tanstack/react-query";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Badge } from "@/components/ui/badge";

export default function BSPComparison() {
  const { data: providers, isLoading } = useQuery({
    queryKey: ["/api/bsp-providers"],
  });

  if (isLoading) {
    return (
      <Card>
        <CardHeader>
          <CardTitle>BSP Performance Comparison</CardTitle>
        </CardHeader>
        <CardContent>
          <div className="animate-pulse">
            <div className="h-64 bg-slate-200 rounded"></div>
          </div>
        </CardContent>
      </Card>
    );
  }

  const getScoreVariant = (score: string) => {
    if (score.includes('A')) return 'default';
    if (score.includes('B')) return 'secondary';
    return 'outline';
  };

  const getScoreColor = (score: string) => {
    if (score.includes('A')) return 'bg-green-100 text-green-800';
    if (score.includes('B')) return 'bg-amber-100 text-amber-800';
    return 'bg-slate-100 text-slate-800';
  };

  const renderProgressBar = (value: string | null) => {
    if (!value) return <span className="text-slate-400 text-sm">N/A</span>;
    
    const numValue = parseInt(value);
    let colorClass = 'bg-red-500';
    if (numValue >= 90) colorClass = 'bg-green-500';
    else if (numValue >= 75) colorClass = 'bg-amber-500';
    
    return (
      <div className="flex items-center space-x-2">
        <div className="w-12 bg-slate-200 rounded-full h-2">
          <div 
            className={`h-2 rounded-full ${colorClass}`}
            style={{ width: `${numValue}%` }}
          ></div>
        </div>
        <span className="text-sm font-medium w-10">{value}%</span>
      </div>
    );
  };

  const getProviderInitials = (name: string) => {
    return name.split(' ').map(word => word[0]).join('').slice(0, 2).toUpperCase();
  };

  const getProviderColor = (name: string) => {
    const colors = [
      'bg-blue-100 text-blue-600',
      'bg-red-100 text-red-600',
      'bg-green-100 text-green-600',
      'bg-purple-100 text-purple-600',
      'bg-amber-100 text-amber-600'
    ];
    return colors[name.length % colors.length];
  };

  return (
    <Card>
      <CardHeader>
        <div className="flex items-center justify-between">
          <CardTitle>BSP Performance Comparison</CardTitle>
          <Select defaultValue="delivery_rate">
            <SelectTrigger className="w-[150px]">
              <SelectValue />
            </SelectTrigger>
            <SelectContent>
              <SelectItem value="delivery_rate">Delivery Rate</SelectItem>
              <SelectItem value="cost_per_message">Cost per Message</SelectItem>
              <SelectItem value="response_time">Response Time</SelectItem>
            </SelectContent>
          </Select>
        </div>
      </CardHeader>
      <CardContent>
        <div className="overflow-x-auto">
          <table className="w-full">
            <thead>
              <tr className="border-b border-slate-200">
                <th className="text-left py-3 px-4 font-medium text-slate-600">Provider</th>
                <th className="text-left py-3 px-4 font-medium text-slate-600">SMS</th>
                <th className="text-left py-3 px-4 font-medium text-slate-600">WhatsApp</th>
                <th className="text-left py-3 px-4 font-medium text-slate-600">Email</th>
                <th className="text-left py-3 px-4 font-medium text-slate-600">Push</th>
                <th className="text-left py-3 px-4 font-medium text-slate-600">Overall Score</th>
              </tr>
            </thead>
            <tbody>
              {providers?.map((provider: any) => (
                <tr key={provider.id} className="border-b border-slate-100 hover:bg-slate-50">
                  <td className="py-3 px-4">
                    <div className="flex items-center space-x-2">
                      <div className={`w-8 h-8 rounded-lg flex items-center justify-center ${getProviderColor(provider.name)}`}>
                        <span className="font-bold text-sm">{getProviderInitials(provider.name)}</span>
                      </div>
                      <span className="font-medium">{provider.name}</span>
                    </div>
                  </td>
                  <td className="py-3 px-4">
                    {renderProgressBar(provider.smsDeliveryRate)}
                  </td>
                  <td className="py-3 px-4">
                    {renderProgressBar(provider.whatsappDeliveryRate)}
                  </td>
                  <td className="py-3 px-4">
                    {renderProgressBar(provider.emailDeliveryRate)}
                  </td>
                  <td className="py-3 px-4">
                    {renderProgressBar(provider.pushDeliveryRate)}
                  </td>
                  <td className="py-3 px-4">
                    <span className={`text-sm px-2 py-1 rounded-full font-medium ${getScoreColor(provider.overallScore)}`}>
                      {provider.overallScore}
                    </span>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </CardContent>
    </Card>
  );
}

// src/app/components/bsp-comparison/bsp-comparison.component.ts
import { Component, OnInit } from '@angular/core';

interface BSPProvider {
  id: string;
  name: string;
  smsDeliveryRate: string | null;
  whatsappDeliveryRate: string | null;
  emailDeliveryRate: string | null;
  pushDeliveryRate: string | null;
  overallScore: string;
}

@Component({
  selector: 'app-bsp-comparison',
  templateUrl: './bsp-comparison.component.html',
  styleUrls: ['./bsp-comparison.component.scss']
})
export class BspComparisonComponent implements OnInit {
  selectedMetric = 'Delivery Rate';
  metricOptions = [
    { label: 'Delivery Rate', value: 'Delivery Rate' },
    { label: 'Cost per Message', value: 'Cost per Message' },
    { label: 'Response Time', value: 'Response Time' }
  ];

  bspProviders: BSPProvider[] = [
    {
      id: '1',
      name: 'Twilio',
      smsDeliveryRate: '94',
      whatsappDeliveryRate: '89',
      emailDeliveryRate: '76',
      pushDeliveryRate: '91',
      overallScore: 'A+'
    },
    {
      id: '2',
      name: 'SendGrid',
      smsDeliveryRate: '78',
      whatsappDeliveryRate: null,
      emailDeliveryRate: '96',
      pushDeliveryRate: null,
      overallScore: 'B+'
    },
    {
      id: '3',
      name: 'Amazon SNS',
      smsDeliveryRate: '87',
      whatsappDeliveryRate: null,
      emailDeliveryRate: '85',
      pushDeliveryRate: '94',
      overallScore: 'B+'
    }
  ];

  constructor() { }

  ngOnInit(): void { }

  getProviderInitials(name: string): string {
    return name.split(' ').map(word => word[0]).join('').slice(0, 2).toUpperCase();
  }

  getProviderColor(name: string): string {
    const colors = ['blue', 'red', 'green', 'purple', 'orange'];
    return colors[name.length % colors.length];
  }

  getScoreColor(score: string): string {
    if (score.includes('A')) return 'bg-green-100 text-green-800';
    if (score.includes('B')) return 'bg-orange-100 text-orange-800';
    return 'bg-surface-100 text-600';
  }

  renderProgressBar(value: string | null): any {
    if (!value) return null;
    
    const numValue = parseInt(value);
    let colorClass = 'red';
    if (numValue >= 90) colorClass = 'green';
    else if (numValue >= 75) colorClass = 'orange';
    
    return {
      value: numValue,
      color: colorClass,
      text: `${value}%`
    };
  }
}
<p-card header="BSP Performance Comparison">
  <ng-template pTemplate="header">
    <div class="flex align-items-center justify-content-between p-4">
      <h3 class="text-lg font-semibold m-0">BSP Performance Comparison</h3>
      <p-dropdown 
        [options]="metricOptions" 
        [(ngModel)]="selectedMetric"
        optionLabel="label"
        optionValue="value"
        [style]="{'min-width': '150px'}">
      </p-dropdown>
    </div>
  </ng-template>
  
  <div class="overflow-x-auto">
    <p-table [value]="bspProviders" styleClass="p-datatable-sm">
      <ng-template pTemplate="header">
        <tr>
          <th class="text-left font-medium text-600">Provider</th>
          <th class="text-left font-medium text-600">SMS</th>
          <th class="text-left font-medium text-600">WhatsApp</th>
          <th class="text-left font-medium text-600">Email</th>
          <th class="text-left font-medium text-600">Push</th>
          <th class="text-left font-medium text-600">Overall Score</th>
        </tr>
      </ng-template>
      <ng-template pTemplate="body" let-provider>
        <tr class="hover:bg-surface-50">
          <td>
            <div class="flex align-items-center gap-2">
              <div class="w-2rem h-2rem border-round-lg flex align-items-center justify-content-center font-bold text-sm"
                   [ngClass]="'bg-' + getProviderColor(provider.name) + '-100 text-' + getProviderColor(provider.name) + '-600'">
                {{getProviderInitials(provider.name)}}
              </div>
              <span class="font-medium">{{provider.name}}</span>
            </div>
          </td>
          <td>
            <div *ngIf="renderProgressBar(provider.smsDeliveryRate) as progress" class="flex align-items-center gap-2">
              <div class="w-3rem bg-surface-200 border-round-2xl" style="height: 8px;">
                <div class="border-round-2xl h-full" 
                     [ngClass]="'bg-' + progress.color + '-500'"
                     [style.width.%]="progress.value"></div>
              </div>
              <span class="text-sm font-medium w-2rem">{{progress.text}}</span>
            </div>
            <span *ngIf="!provider.smsDeliveryRate" class="text-400 text-sm">N/A</span>
          </td>
          <td>
            <div *ngIf="renderProgressBar(provider.whatsappDeliveryRate) as progress" class="flex align-items-center gap-2">
              <div class="w-3rem bg-surface-200 border-round-2xl" style="height: 8px;">
                <div class="border-round-2xl h-full" 
                     [ngClass]="'bg-' + progress.color + '-500'"
                     [style.width.%]="progress.value"></div>
              </div>
              <span class="text-sm font-medium w-2rem">{{progress.text}}</span>
            </div>
            <span *ngIf="!provider.whatsappDeliveryRate" class="text-400 text-sm">N/A</span>
          </td>
          <td>
            <div *ngIf="renderProgressBar(provider.emailDeliveryRate) as progress" class="flex align-items-center gap-2">
              <div class="w-3rem bg-surface-200 border-round-2xl" style="height: 8px;">
                <div class="border-round-2xl h-full" 
                     [ngClass]="'bg-' + progress.color + '-500'"
                     [style.width.%]="progress.value"></div>
              </div>
              <span class="text-sm font-medium w-2rem">{{progress.text}}</span>
            </div>
            <span *ngIf="!provider.emailDeliveryRate" class="text-400 text-sm">N/A</span>
          </td>
          <td>
            <div *ngIf="renderProgressBar(provider.pushDeliveryRate) as progress" class="flex align-items-center gap-2">
              <div class="w-3rem bg-surface-200 border-round-2xl" style="height: 8px;">
                <div class="border-round-2xl h-full" 
                     [ngClass]="'bg-' + progress.color + '-500'"
                     [style.width.%]="progress.value"></div>
              </div>
              <span class="text-sm font-medium w-2rem">{{progress.text}}</span>
            </div>
            <span *ngIf="!provider.pushDeliveryRate" class="text-400 text-sm">N/A</span>
          </td>
          <td>
            <p-tag 
              [value]="provider.overallScore"
              [ngClass]="getScoreColor(provider.overallScore)"
              styleClass="text-sm font-medium">
            </p-tag>
          </td>
        </tr>
      </ng-template>
    </p-table>
  </div>
</p-card>
